Lesson 01
sanyco86/blog-platform pull request #1
Opened 2016-12-13 16:31 UTC by sanyco86

2016-12-14 08:44 UTC, index01d requested changes
С одной стороны похвально применение системы сборки. С другой: в проекте есть лишние зависимости. Я рекомендую следовать правилу "не добавлять зависимости пока они не понадобятся".  Поэтому прошу вычистить лишние зависимости. Кроме того, компонент Image не соответствует заданию, часть значений (высоту, ширину и alt) нужно параметризовать с помощью свойств.

2016-12-14 08:44 UTC, index01d commented on webpack.config.js
> +        new NpmInstallPlugin
Не ясно зачем нам это здесь

2016-12-14 08:44 UTC, index01d commented on package.json
> +    "redux-logger": "2.7.4",
очевидно лишние зависимости

2016-12-14 08:44 UTC, index01d commented on package.json
> +    "lodash": "4.17.2",
должен быть в основных зависимостях

2016-12-14 08:44 UTC, index01d commented on package.json
> +    "express": "^4.14.0",
должен быть в основных зависимостях

2016-12-14 08:44 UTC, index01d commented on index.html
> +    <script src="https://code.jquery.com/jquery.min.js"></script>
не ясно зачем нам нужен jquery

2016-12-14 08:44 UTC, index01d commented on package.json
> +    "postcss-loader": "1.2.0",
postcss добавлен, но не используется в проекте

2016-12-14 08:44 UTC, index01d commented on server.js
> +var compiler = webpack(config);
можно решить без вебпака и генерации статической страницы, просто сформировав строку для ответа при помощь ReactDOMServer.renderToString

2016-12-14 08:44 UTC, index01d commented on server.js
> +var compiler = webpack(config);
не принципиально, так как таким образом подгружаются стили.

2016-12-14 08:44 UTC, index01d commented on src/components/Image.js
> +            <img src={require(`../assets/images/${this.props.img}`)} style={{width: '100%', height: '305px'}} alt='Post'/>
высота, ширина и alt картинки должны быть получены из свойств

2016-12-15 06:14 UTC, sanyco86 commented on webpack.config.js
> +        new NpmInstallPlugin
для автоматической установки зависимостей, если я забыл что-то включить. Возможно это и стало причиной того, что у меня в `package.json` появились лишние зависимости.

2016-12-15 06:30 UTC, sanyco86 commented on package.json
> +    "postcss-loader": "1.2.0",
почему не используется, я же подключил css стили к приложению

2016-12-15 07:56 UTC, index01d commented on webpack.config.js
> +        new NpmInstallPlugin
крайне вредная практика, как по мне:) лучше контролировать число зависимостей в проекте, так как это сильно влияет на итоговый размер bundle и сложность дерева зависимостей.

2016-12-15 08:02 UTC, index01d requested changes
В предыдущем комментарии я имел ввиду, что данные о картинке должны приходить вместе с ссылкой на нее извне. То есть в массиве items информация о картинке может быть представлена объектом с ключами src, width, height. Данные ключи должны быть свойствами (ключами props) компонента Image.

2016-12-15 08:31 UTC, index01d approved these changes
:)

2016-12-20 11:21 UTC, merged