lesson 03
sanyco86/blog-platform pull request #4
Opened 2016-12-27 14:58 UTC by sanyco86

2016-12-27 23:46 UTC, index01d approved these changes

2016-12-27 23:49 UTC, index01d requested changes
поспешил прувнуть. Нашел неточность.

2016-12-27 23:49 UTC, index01d commented on src/containers/BlogPage.js
> +            if (item.id === itemId) ++item.meta.likes;
похоже, что второй раз лайк поставить не удастся?

2016-12-27 23:50 UTC, index01d commented on src/containers/BlogPage.js
> +            if (item.id === itemId) ++item.meta.likes;
или так задумано?:)

2016-12-28 04:47 UTC, sanyco86 commented on src/containers/BlogPage.js
> +            if (item.id === itemId) ++item.meta.likes;
Да нет. Лайкает сколько угодно. Какой хочешь пост, количество меняется, график крутится )))

2016-12-28 04:49 UTC, sanyco86 commented on src/containers/BlogPage.js
> +            if (item.id === itemId) ++item.meta.likes;
А что не так то ?

2016-12-28 06:56 UTC, sanyco86 commented on src/containers/BlogPage.js
> +            if (item.id === itemId) ++item.meta.likes;
https://www.dropbox.com/s/m578ksuuwda4cp9/lesson-03.mov?dl=0

2016-12-28 07:52 UTC, index01d commented on src/containers/BlogPage.js
> +            if (item.id === itemId) ++item.meta.likes;
потому что мутирует исходник, ну не состояние да и ладно. Думаю мы к этому еще вернемся через урок:)

2016-12-28 07:53 UTC, index01d approved these changes

2016-12-29 05:30 UTC, merged