Lesson 05
sanyco86/blog-platform pull request #5
Opened 2017-01-24 09:01 UTC by sanyco86

2017-01-24 10:56 UTC, index01d commented on src/components/Post.js
> +    this.setState(fetchPosts);
```
fetchPosts((items) => this.setState({items}))
```

2017-01-24 10:57 UTC, index01d commented on src/components/Post.js
> +    this.setState(fetchPosts);
функцию fetchPosts, соответственно надо переписать чтобы она принимала аргументом эту функцию и вызывала ее

2017-01-26 18:03 UTC, index01d requested changes
Линтер имеет список из 20 проблем для недовольства.

2017-01-26 18:03 UTC, index01d commented on src/components/elements/NavLink.js
> +import { Link } from 'react-router'
раз сделали Link, то лучше из него и импортировать, не из react-router

2017-01-26 18:03 UTC, index01d commented on src/components/SupportAs.js
> +export default class SupportAs extends Component {
мог бы быть stateless

2017-01-26 18:03 UTC, index01d commented on src/components/layouts/Main.js
> +      <div className='main'>
с учетом того, что верстка может усложняться я бы декомпозировал на

- Container
  - Header
  - Footer

Но сейчас это не слишком принципиально

2017-01-26 18:03 UTC, index01d commented on src/components/layouts/Main.js
> +        <div className='header'><Header /></div>
непонятно зачем Header обернут в кусок header'a

2017-01-26 18:03 UTC, index01d commented on src/components/layouts/Main.js
> +import Header from '../../containers/Header'
ключ.слово containers обычно используется в контексте разделения на контейнерные-презентационные компоненты. В данном случае Header - презентационный компонент, поэтому я бы предложил сделать Main директорией, в index.js разместить текущее содержимое Main.js, рядом положить Header.js, SideBarMenu.js и Footer.js и подключать их с ./ (предполагаю, что эти компоненты нигде кроме MainLayout'a использоваться не будут)

2017-01-26 18:03 UTC, index01d commented on src/components/layouts/Main.js
> +import Header from '../../containers/Header'
При этом BlogPage остается контейнером, так как он им является с тз разделения логики

2017-01-26 18:03 UTC, index01d commented on src/components/layouts/Main.js
> +          <div className='content_resize'>
предыдущие две строки могли бы стать компонентом Content

2017-01-26 18:03 UTC, index01d commented on src/components/elements/NavLink.js
> +    let className = isActive ? 'active' : '';
Для условного выставления классов рекомендую притянуть библиотеку `classnames` (https://github.com/JedWatson/classnames) С ее помощью можно задать классы так:
`<li className={classNames({ isActive: <условие> })}>`.

Однако в данном случае можно просто сделать компонент stateless и выставлять активность с помощью специального свойства компонента Link:
```
const NavLink = ({ to, className }) => (
  <li className={className}>
    <Link to={to} activeClassName='active' />
  </li>
)
```

React-router сам сделает необходимое сопоставление с контекстом

2017-01-26 18:03 UTC, index01d commented on src/components/layouts/Main.js
> +            <div className='clr'></div>
очень желательно избавляться от таких div'ов
а) плохо с точки зрения SEO
б) плохо с точки зрения семантики и чистоты html-кода, div совсем не для этого предназначен
в) плохо с точки зрения чистоты функции рендера: если избавиться от служебных пустых дивов, то можно будет добиться хорошей декомпозиции на семантически-значимые компоненты

2017-02-01 09:49 UTC, index01d requested changes
Предлагаю навести порядок с точки зрения разделения контейнерной-презентационной логики, декомпозиции сложных функций render на функциональные компоненты (я понимаю, что они приехали с шаблоном, но хотя бы "бутафорно" надо их оформить в компоненты). Также сделал несколько замечаний по функциям внутри функции render вместо оформления еще одного обычного компонента. За счет этого многие презентационные компоненты можно было бы сделать stateless

2017-02-01 09:49 UTC, index01d commented on src/components/ContactAs.js
> +export default class ContactAs extends Component {
ContactUs ;)

2017-02-01 09:49 UTC, index01d commented on src/components/Post.js
> +      <div className='mainbar'>
презентационная логика в контейнерном компоненте. Не слишком хорошо.

2017-02-01 09:49 UTC, index01d commented on src/components/layouts/Main/Footer.js
> +export default class Footer extends Component {
Хорошо бы его декомпозировать конечно.

2017-02-01 09:49 UTC, index01d commented on src/components/layouts/Main/Footer.js
> +              <a href='skype:sanyco86?chat'>sanyco86</a>
Должно быть константами

2017-02-01 09:49 UTC, index01d commented on src/components/layouts/Main/Header.js
> +export default class Header extends Component {
Также хорошо бы его декомпозировать конечно.

2017-02-01 09:49 UTC, index01d commented on src/components/layouts/Main/Header.js
> +              <NavLink to='/'><span>Home Page</span></NavLink>
Меню точно должно быть отдельным компонентом

2017-02-01 09:49 UTC, index01d commented on src/components/widgets/BlogList.js
> +      blogTemplate = items.map(
почему не отдельный компонент или состав BlogItem?

2017-02-01 09:49 UTC, index01d commented on src/components/widgets/blog/elements/BlogInfo.js
> +    const tags = meta.tags.map(
почему не отдельный компонент?

2017-02-01 09:49 UTC, index01d commented on src/components/widgets/blog/elements/Like.js
> +export default class Like extends Component {
Нужно разделить на контейнер и презентационный компонент

2017-02-01 09:49 UTC, index01d commented on src/containers/BlogPage.js
> +        <p className='pages'>
Нужно декомпозировать в отдельный компонент

2017-02-01 09:49 UTC, index01d commented on src/containers/BlogPage.js
> +      <div className='mainbar'>
Презентационный элемент в контейнере

2017-02-01 09:49 UTC, index01d commented on src/routes/Blog.js
> +  path: '/about',
я бы рекомендовал также обернуть в pathHelper

2017-02-01 09:49 UTC, index01d commented on src/routes/Blog.js
> +  path: '/about',
так как этот путь может меняться

2017-02-01 09:49 UTC, index01d commented on src/routes/Blog.js
> +  path: '/about',
аналогично support, contact

2017-02-02 09:57 UTC, sanyco86 commented on src/routes/Blog.js
> +  path: '/about',
Все теперь я окончательно запутался, что где и для чего должно быть.

2017-02-02 09:58 UTC, sanyco86 commented
@index01d Все теперь я окончательно запутался, что где и для чего должно быть.

2017-02-02 10:01 UTC, sanyco86 commented
@index01d я понятия не имею что означают слова
декомпозировать, презентационная логика и т.д.
и не могу понять, что действительно от меня требуется сделать

2017-02-04 07:54 UTC, index01d commented
хорошо, я сегодня распишу чуть подробнее

2017-02-05 09:33 UTC, index01d commented on src/components/Post.js
> +      <div className='mainbar'>
Я имею ввиду, что в контейнерном компоненте не должно быть элементов DOM-дерева (об этом я упоминал в первом уроке курса), такой компонент должен приготовить данные+колбэки и отправить их презентационному компоненту, который уже будет отображать DOM-элементы

2017-02-05 09:34 UTC, index01d commented on src/components/layouts/Main/Footer.js
> +export default class Footer extends Component {
Под декомпозицией в данном случае имеется ввиду разделение компонента на несколько. Сейчас футер очевидно содержит в себе несколько текстовых блоков, меню, блок контактов.

2017-02-05 09:35 UTC, index01d commented on src/components/layouts/Main/Header.js
> +export default class Header extends Component {
То же самое с верхней частью страницы, правильно было бы выделить компонент меню, форму поиска, логотип

2017-02-05 09:39 UTC, index01d commented
Добавил немного комментариев к своим же комментариям. Надеюсь, что станет чуточку понятнее. Если не станет, то можно пока не заморачиваться, т.к. по ходу дела мы к этим вопросам еще вернемся. Насчет размещения файлов я отписался на форуме в треде домашнего задания.

2017-02-10 06:53 UTC, merged