lesson 6
sanyco86/blog-platform pull request #6
Opened 2017-02-10 12:47 UTC by sanyco86

2017-02-10 13:53 UTC, index01d requested changes

2017-02-10 13:53 UTC, index01d commented on src/components/widgets/blog/elements/BlogInfo.js
>  import { retrieveDate } from '../../../../helpers/Date'
лучше не использовать относительные пути, писать просто `from 'helpers/Date'`

2017-02-10 13:54 UTC, index01d commented
в остальном выглядит неплохо

2017-02-10 13:59 UTC, sanyco86 commented on src/components/widgets/blog/elements/BlogInfo.js
>  import { retrieveDate } from '../../../../helpers/Date'
а у меня почему то так не находит. я бы рад обходиться без этой лупой навигации, когда нужно прыгать назад через ../

2017-02-11 10:41 UTC, index01d commented on src/components/widgets/blog/elements/BlogInfo.js
>  import { retrieveDate } from '../../../../helpers/Date'
нужно задать root ключ в конфигурации webpack. пример: https://github.com/indevelope/blog/blob/master/webpack.config.js#L41

2017-03-01 08:41 UTC, merged